<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
--- SUBIDA DE ARCHIVO:
EJERCICIO SUBIDA ARCHIVO (IMAGENES):

OPCIONAL: UNA VEZ FINALIZADA LA PRACTICA 2, INCLUIR EN EL 
FORMULARIO DE REGISTRO DEL TIPO DE DATA ELEGIDO UN CAMPO 
TIPO FILE DONDE UN ADMINISTRADOR PODRA SUBIR UNA IMAGEN 
ASOCIADA AL TIPO DE DATO, LA CUAL DEBERA APARECER 
EN LOS LISTADOS.

OPCIONAL 2: PERMITIR MODIFICAR LA IMAGEN EN LA PARTE 
DE MODIFICAR DATOS. 

OPCIONAL 3: BORRAR TAMBIEN LA IMAGEN ASOCIADA CUANDO SE BORRE
EL REGISTRO CORRESPONDIENTE.

---- ASOCIACIONES:

OPCIONAL 1: CREAR UNA TABLA DE CATEGORIAS PARA PODER ASOCIAR UNO DE LOS 
DOS TIPOS DE DATOS DE LA PRACTICA A UNA CATEGORIA COMO SE HA MOSTRADO EN LOS 
EJEMLOS, EN EL LISTO DEL TIPO DE DATO MOSTRAR TAMBIEN SU CATEGORIA

OPCIONAL 2: PERMITIR CREAR, EDITAR, LISTAR Y BORRAR CATEGORIAS.

---- PAGINACION:

OPCIONAL 1: INCLUIR PAGINACION EN LOS LISTADOS DE INFORMACIONES.

-- BUSCADOR:

OPCIONAL 1: INCLUIR UN BUSCADOR EN LOS LISTADOS

<div>gestion tienda online</div>
<a href="ServletPreparaRegistroProducto">registrar nuevo producto</a> 
<a href="ServletListadoProductos?desde=0&cuantos=20">listado de productos</a> 


</body>
</html>



